---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: clusterdeployments.hmc.mirantis.com
spec:
  group: hmc.mirantis.com
  names:
    kind: ClusterDeployment
    listKind: ClusterDeploymentList
    plural: clusterdeployments
    shortNames:
    - clusterd
    - cld
    singular: clusterdeployment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Ready
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: ready
      type: string
    - description: Status
      jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: status
      type: string
    - description: Dry Run
      jsonPath: .spec.dryRun
      name: dryRun
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterDeployment is the Schema for the ClusterDeployments API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterDeploymentSpec defines the desired state of ClusterDeployment
            properties:
              config:
                description: |-
                  Config allows to provide parameters for template customization.
                  If no Config provided, the field will be populated with the default values for
                  the template and DryRun will be enabled.
                x-kubernetes-preserve-unknown-fields: true
              credential:
                description: Name reference to the related Credentials object.
                type: string
              dryRun:
                description: DryRun specifies whether the template should be applied
                  after validation or only validated.
                type: boolean
              propagateCredentials:
                default: true
                description: |-
                  PropagateCredentials indicates whether credentials should be propagated
                  for use by CCM (Cloud Controller Manager).
                type: boolean
              services:
                description: |-
                  Services is a list of services created via ServiceTemplates
                  that could be installed on the target cluster.
                items:
                  description: ServiceSpec represents a Service to be managed
                  properties:
                    disable:
                      description: Disable can be set to disable handling of this
                        service.
                      type: boolean
                    name:
                      description: Name is the chart release.
                      maxLength: 253
                      minLength: 1
                      type: string
                    namespace:
                      description: |-
                        Namespace is the namespace the release will be installed in.
                        It will default to Name if not provided.
                      type: string
                    template:
                      description: Template is a reference to a Template object located
                        in the same namespace.
                      maxLength: 253
                      minLength: 1
                      type: string
                    values:
                      description: |-
                        Values is the helm values to be passed to the chart used by the template.
                        The string type is used in order to allow for templating.
                      type: string
                  required:
                  - name
                  - template
                  type: object
                type: array
              servicesPriority:
                default: 100
                description: |-
                  ServicesPriority sets the priority for the services defined in this spec.
                  Higher value means higher priority and lower means lower.
                  In case of conflict with another object managing the service,
                  the one with higher priority will get to deploy its services.
                format: int32
                maximum: 2147483646
                minimum: 1
                type: integer
              stopOnConflict:
                default: false
                description: |-
                  StopOnConflict specifies what to do in case of a conflict.
                  E.g. If another object is already managing a service.
                  By default the remaining services will be deployed even if conflict is detected.
                  If set to true, the deployment will stop after encountering the first conflict.
                type: boolean
              template:
                description: Template is a reference to a Template object located
                  in the same namespace.
                maxLength: 253
                minLength: 1
                type: string
            required:
            - template
            type: object
          status:
            description: ClusterDeploymentStatus defines the observed state of ClusterDeployment
            properties:
              availableUpgrades:
                description: |-
                  AvailableUpgrades is the list of ClusterTemplate names to which
                  this cluster can be upgraded. It can be an empty array, which means no upgrades are
                  available.
                items:
                  type: string
                type: array
              conditions:
                description: Conditions contains details for the current state of
                  the ClusterDeployment.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              k8sVersion:
                description: |-
                  Currently compatible exact Kubernetes version of the cluster. Being set only if
                  provided by the corresponding ClusterTemplate.
                type: string
              observedGeneration:
                description: ObservedGeneration is the last observed generation.
                format: int64
                type: integer
              services:
                description: Services contains details for the state of services.
                items:
                  description: ServiceStatus contains details for the state of services.
                  properties:
                    clusterName:
                      description: ClusterName is the name of the associated cluster.
                      type: string
                    clusterNamespace:
                      description: ClusterNamespace is the namespace of the associated
                        cluster.
                      type: string
                    conditions:
                      description: Conditions contains details for the current state
                        of managed services.
                      items:
                        description: Condition contains details for one aspect of
                          the current state of this API Resource.
                        properties:
                          lastTransitionTime:
                            description: |-
                              lastTransitionTime is the last time the condition transitioned from one status to another.
                              This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                            format: date-time
                            type: string
                          message:
                            description: |-
                              message is a human readable message indicating details about the transition.
                              This may be an empty string.
                            maxLength: 32768
                            type: string
                          observedGeneration:
                            description: |-
                              observedGeneration represents the .metadata.generation that the condition was set based upon.
                              For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                              with respect to the current state of the instance.
                            format: int64
                            minimum: 0
                            type: integer
                          reason:
                            description: |-
                              reason contains a programmatic identifier indicating the reason for the condition's last transition.
                              Producers of specific condition types may define expected values and meanings for this field,
                              and whether the values are considered a guaranteed API.
                              The value should be a CamelCase string.
                              This field may not be empty.
                            maxLength: 1024
                            minLength: 1
                            pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                            type: string
                          status:
                            description: status of the condition, one of True, False,
                              Unknown.
                            enum:
                            - "True"
                            - "False"
                            - Unknown
                            type: string
                          type:
                            description: type of condition in CamelCase or in foo.example.com/CamelCase.
                            maxLength: 316
                            pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                            type: string
                        required:
                        - lastTransitionTime
                        - message
                        - reason
                        - status
                        - type
                        type: object
                      type: array
                  required:
                  - clusterName
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
