# Cluster parameters
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
      - "10.244.0.0/16"
  services:
    cidrBlocks:
      - "10.96.0.0/12"

# AWS cluster parameters
vpcID: ""
region: ""
sshKeyName: ""
publicIP: false
subnets:
  - id: ""
    availabilityZone: ""
bastion:
  enabled: false
  disableIngressRules: false
  allowedCIDRBlocks: []
  instanceType: t2.micro
  ami: ""
clusterIdentity:
  name: ""
  kind: "AWSClusterStaticIdentity"
# AWS machines parameters
amiID: ""
imageLookup:
  format: "amzn2-ami-hvm*-gp2"
  org: "137112412989"
  baseOS: ""
iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
instanceType: ""
securityGroupIDs: []
rootVolumeSize: 8

# K0smotron parameters
k0smotron:
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132

# K0s parameters
k0s:
  version: v1.31.1+k0s.1
