# Cluster parameters
controlPlaneNumber: 3
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"

# Azure cluster parameters
location: ""
subscriptionID: ""
bastion:
  enabled: false
  bastionSpec:
    azureBastion: {}
clusterIdentity:
  name: ""
  namespace: hmc-system
resourceGroup: ""
network:
  vnetName: ""
  nodeSubnetName: ""
  routeTableName: ""
  securityGroupName: ""
# Azure machines parameters

sshPublicKey: ""
vmSize: ""
rootVolumeSize: 30
image:
  marketplace:
    publisher: "cncf-upstream"
    offer: "capi"
    sku: "ubuntu-2204-gen1"
    version: "130.3.20240717"

# K0smotron parameters
k0smotron:
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132

# K0s parameters
k0s:
  version: v1.31.1+k0s.1

# extensions defines custom Helm and image repositories to use for pulling
# k0s extensions.
extensions:
  chartRepository: ""
  imageRepository: ""
