configSecret:
  create: true
  name: "vsphere-variables"
  namespace: ""

airgap: false

config:
  VSPHERE_USERNAME: ""
  VSPHERE_PASSWORD: ""
  KUBERNETES_VERSION: ""
  VSPHERE_SERVER: ""
  VSPHERE_DATACENTER: ""
  VSPHERE_DATASTORE: ""
  VSPHERE_NETWORK: ""
  VSPHERE_RESOURCE_POOL: ""
  VSPHERE_FOLDER: ""
  VSPHERE_TEMPLATE: ""
  CONTROL_PLANE_ENDPOINT_IP: ""
  VSPHERE_TLS_THUMBPRINT: ""
  EXP_CLUSTER_RESOURCE_SET: ""
  VSPHERE_SSH_AUTHORIZED_KEY: ""
  VSPHERE_STORAGE_POLICY: ""
  CPI_IMAGE_K8S_VERSION: ""
