# Cluster parameters
controlPlaneNumber: 3
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"

# vSphere cluster parameters
clusterIdentity:
  name: ""
vsphere:
  server: ""
  thumbprint: ""
  datacenter: ""
  datastore: ""
  resourcePool: ""
  folder: ""
controlPlaneEndpointIP: ""

# vSphere machines parameters
ssh:
  user: ""
  publicKey: ""
rootVolumeSize: 30
cpus: 2
memory: 4096
vmTemplate: ""
network: ""

# K0smotron parameters
k0smotron:
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132

# K0s parameters
k0s:
  version: v1.31.1+k0s.1

# extensions defines custom Helm and image repositories to use for pulling
# k0s extensions.
extensions:
  chartRepository: ""
  imageRepository: ""
