apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-awsprovider-viewer-role
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - awsprovider
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - awsprovider/status
  verbs:
  - get