apiVersion: v1
data:
  value: ${KUBECONFIG_DATA}
kind: Secret
metadata:
  name: adopted-cluster-kubeconf
  namespace: ${NAMESPACE}
type: Opaque
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: adopted-cluster-cred
  namespace: ${NAMESPACE}
spec:
  description: Adopted Credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: adopted-cluster-kubeconf
    namespace: ${NAMESPACE}