apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: azure-aks-dev
  namespace: ${NAMESPACE}
spec:
  template: azure-aks-0-0-1
  credential: azure-aks-credential
  propagateCredentials: false
  config:
    location: "westus"
    machinePools:
      system:
        count: 1
        vmSize: Standard_A4_v2
      user:
        count: 1
        vmSize: Standard_A4_v2
