---
apiVersion: v1
kind: Secret
metadata:
  name: azure-aks-credential
  namespace: ${NAMESPACE}
stringData:
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
  AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
  AZURE_SUBSCRIPTION_ID: "${AZURE_SUBSCRIPTION_ID}"
  AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
type: Opaque
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-aks-credential
  namespace: ${NAMESPACE}
spec:
  description: Azure AKS credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: azure-aks-credential
    namespace: ${NAMESPACE}
