---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: aws-cluster-identity
  namespace: ${NAMESPACE}
spec:
  secretRef: aws-cluster-identity-secret
  allowedNamespaces:
    selector:
      matchLabels: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cluster-identity-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  AccessKeyID: ${AWS_ACCESS_KEY_ID}
  SecretAccessKey: ${AWS_SECRET_ACCESS_KEY}
